# Run the following command to build the site in production mode. It is required to minify the CSS and JS files.
# $env:JEKYLL_ENV="production"
# bundle exec jekyll build


title: NIJobair
description: A continuous learner.
author: Nazmul Islam

show_downloads: false

url: "https://nijobair.github.io"
baseurl: ""

markdown: kramdown

kramdown:
  syntax_highlighter: None
  syntax_highlighter_opts:
    disable : true


# SASS configuration
sass_dir: _sass
sass:
  load_paths:
    - "assets/css"
    - "_sass"


# Define collection directories
collections_dir: my_collections
collections:
  projects:
    output: true
  sqlChallengeHub:
    output: true


# Layouts
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:categories/:title/
  
  -
    scope:
      path: ""
      type: projects
    values:
      layout: post
      permalink: /projects/:title/


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-glossary_tooltip
  - jekyll-avatar
  - jekyll-feed


# Enable compression and minification
assets:
  compress:
    css: true
    js: true
    


# Exclude files from the build
exclude:
  - assets/templates
  - _deneb
  - Gemfile
  - Gemfile.lock
  - README.md
  - __Extras
  - my_collections/_posts/_drafts
  - my_collections/_projects/_drafts
  - blog.css
  - global.css
  - homePage.css
  - others.css
  - sqlChallengeHub.css
  - accordion.css
  - blog.js
  - highlight.js
  - annotateScrollbar.js
  - closeBrackets.js
  - codeMirror.js
  - comment.js
  - fullScreen.js
  - matchBrackets.js
  - matchHighlighter.js
  - matchOnScrollbar.js
  - placeHolder.js
  - searchCursor.js
  - sqlChallengeHub.js
  - sqlCodeMirror.js

  