title: NIJobair
description: A continuous learner.
author: Nazmul Islam

show_downloads: false

url: "https://nijobair.github.io"
baseurl: ""

markdown: kramdown

kramdown:
  syntax_highlighter: None
  syntax_highlighter_opts:
    disable : true


sass_dir: _sass
sass:
  load_paths:
    - "assets/css"
    - "_sass"



collections_dir: my_collections
collections:
  projects:
    output: true
  deneb:
    output: true
  blog:
    output: true


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:categories/:title/
  
  -
    scope:
      path: ""
      type: projects
    values:
      layout: post
      permalink: /projects/:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-glossary_tooltip
  - jekyll-avatar
  - jekyll-feed

exclude:
  - assets/templates
  - _deneb
  - Gemfile
  - Gemfile.lock
  - README.md
  - __Extras
  - my_collections/_posts/_drafts
  - my_collections/_projects/_drafts
  