# Run the following command to build the site in production mode. It is required to minify the CSS and JS files.
# $env:JEKYLL_ENV="production"
# bundle exec jekyll build


title: NIJobair
description: A continuous learner.
author: Nazmul Islam

show_downloads: false

url: "https://nijobair.github.io"
baseurl: ""

markdown: kramdown

kramdown:
  syntax_highlighter: None
  syntax_highlighter_opts:
    disable : true


# SASS configuration
sass_dir: _sass
sass:
  load_paths:
    - "assets/css"
    - "_sass"


# Define collection directories
collections_dir: my_collections
collections:
  projects:
    output: true
  sqlChallengeHub:
    output: true


# Layouts
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:categories/:title/
  
  -
    scope:
      path: ""
      type: projects
    values:
      layout: post
      permalink: /projects/:categories/:title/


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-glossary_tooltip
  - jekyll-avatar
  - jekyll-feed
  - jekyll-loading-lazy    


# Exclude files from the build
exclude:
  - assets/templates
  - _deneb
  - Gemfile
  - Gemfile.lock
  - README.md
  - __Extras
  - my_collections/_posts/_drafts
  - my_collections/_projects/_drafts
  - assets/css/blog.css
  - assets/css/global.css
  - assets/css/homePage.css
  - assets/css/others.css
  - assets/css/sqlChallengeHub.css
  - assets/css/accordion.css
  - assets/js/blog.js
  - assets/js/highlight.js
  - assets/js/sqlChallengeHub/annotateScrollbar.js
  - assets/js/sqlChallengeHub/closeBrackets.js
  - assets/js/sqlChallengeHub/codeMirror.js
  - assets/js/sqlChallengeHub/comment.js
  - assets/js/sqlChallengeHub/fullScreen.js
  - assets/js/sqlChallengeHub/matchBrackets.js
  - assets/js/sqlChallengeHub/matchHighlighter.js
  - assets/js/sqlChallengeHub/matchOnScrollbar.js
  - assets/js/sqlChallengeHub/placeHolder.js
  - assets/js/sqlChallengeHub/searchCursor.js
  - assets/js/sqlChallengeHub/sqlChallengeHub.js
  - assets/js/sqlChallengeHub/sqlCodeMirror.js

  